apiVersion: v1
kind: Service
metadata:
  name: hello-python31
spec:
  selector:
    app: hello-python31
  ports:
  - name: http
    protocol: TCP
    port: 6002
    targetPort: 5000
  type: LoadBalancer


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-python31
  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-python31
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: hello-python31
    spec:
      containers:
      - name: hello-python31
        image: phanick/hello-python31:11
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        
